### ISSUE TITLE
Internal Server Error for repo links

### ISSUE THREAD

**Issue by bryangingechen** [schme16/gitcdn.xyz#58] opened 2020-01-18 16:21 UTC
For example: https://gitcdn.link/repo/schme16/gitcdn.xyz/master/LICENSE

and https://gitcdn.xyz/repo/schme16/gitcdn.xyz/master/LICENSE

**Comment by bryangingechen** [comment] 2020-01-18 16:45
Seems to be working again...

**Comment by milankragujevic** [comment] 2020-01-26 17:23
The problem is occurring again.

https://gitcdn.xyz/repo/enyo/dropzone/master/dist/min/dropzone.min.js

@bryangingechen please reopen the issue.

**Comment by forger** [comment] 2020-01-31 17:18
Had the same issue (with a different URL) for some time today - then it went away.

**Comment by rivy** [comment] 2020-03-08 18:18
+1 today

**Comment by natxocc** [comment] 2020-03-23 16:55
+1 today

**Comment by theArtechnology** [comment] 2020-04-01 18:39
+1 today

**Comment by RubyistCTRLDYT** [comment] 2020-05-01 21:13
+1 today

**Comment by cocomine** [comment] 2020-08-31 13:36
It happened again today

**Comment by schme16** [comment] 2020-10-22 23:56
See #60 for more details about the why this occured, and why it's fixed now, but suffice to say that it should be occuring extreamly rarely from now on

**Closed by schme16** 2020-10-22 23:56 UTC
Labels: bug, outage
